name: "Check for IT Change ID in PR title"
description: "Checks for IT Change ID in PR title"

runs:
  using: "composite"
  steps:
    - name: "Checkout codebase"
      uses: actions/checkout@v4

    - name: "Check for IT Change ID"
      run: |
        echo "Hello world"
        pwd
        echo ${{ github.repository }}
        echo
        echo
        echo "Here is the list of merged PRs"
        echo
        gh pr list --state closed
        echo
        latest_pr_number=$(gh pr list --state closed | grep "Release" | grep -E "[0-9]*\.[0-9]*\.[0-9]* " | head -1)
        echo
        echo "Latest PR is:"
        echo
        echo $latest_pr_number
        echo
        TEST_COMMAND=$(echo ${latest_pr_number} | grep -E -q "\- IT Change #[0-9]*")
        RETURN_CODE=$?
        if [ $RETURN_CODE -eq 0 ]; then
          echo "PR title looks good"
        else
          echo "PR title doesn't comply with the format:"
          echo "<Something something ..> - IT Change #<number>"
          exit 1
        fi
        echo

      shell: bash
