name: "Check for IT Change ID in PR title"
description: "Checks for IT Change ID in PR title"

runs:
  using: "composite"
  steps:
    - name: "Checkout codebase"
      uses: actions/checkout@v4

    - name: "Check for IT Change ID"
      run: |
        echo "Hello world"
        pwd
        echo ${{ github.repository }}
        echo
        echo
        gh
        echo
        echo
      shell: bash
