name: "Check for IT Change ID in PR title"
description: "Checks for IT Change ID in PR title"

runs:
  using: "composite"
  steps:
    - name: "Checkout codebase"
      uses: actions/checkout@v4
      with:
        repository: nn-dma/link-work-item
        path: .
        fetch-depth: 0

    - name: "Check for IT Change ID"
      run: |
        cd scripts
        echo "{{ github.sha }}: ${{ env.GH_SHA }}"
        echo "{{ env.GH_TOKEN }}: ${{ env.GH_TOKEN }}"
        echo "{{ github.repository }}: ${{ github.repository }}"
        export GITHUB_TOKEN=${{ env.GH_TOKEN }}
        env
        gh pr list --state closed
        echo
        echo AAAAAAAAA
        echo
        if [ `gh pr list --state closed | grep -E " - IT Change #[0-9]+$"` ]; then
          echo "IT Change title is compliant"
        else
          gh pr list --state closed
          echo "Couldn't any closed PR with IT Change title."
          echo "It should look like this: 'Release 1.0.0 - IT Change #1234'"
          exit 1
        fi
      shell: bash
